[package]
name = "vt100"
version = "0.15.1"
authors = ["Jesse Luehrs <doy@tozt.net>"]
edition = "2021"

description = "Library for parsing terminal data"
homepage = "https://github.com/doy/vt100-rust"
repository = "https://github.com/doy/vt100-rust"
readme = "README.md"
keywords = ["terminal", "vt100"]
categories = ["command-line-interface", "encoding"]
license = "MIT"
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]

[dependencies]
itoa = "1.0.3"
log = "0.4.17"
unicode-width = "0.1.9"
vte = "0.11.0"

[dev-dependencies]
nix = "0.23.0"
quickcheck = "0.9"
rand = "0.7"
serde = { version = "1.0.131", features = ["derive"] }
serde_json = "1.0.73"
terminal_size = "0.1.17"
vte = "0.10.1"
